# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1051, 661))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_4.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_4.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 1, 3, 1, 1)
        self.progressBar1_3 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_3.sizePolicy().hasHeightForWidth())
        self.progressBar1_3.setSizePolicy(sizePolicy)
        self.progressBar1_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_3.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_3.setAutoFillBackground(False)
        self.progressBar1_3.setProperty("value", 25)
        self.progressBar1_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_3.setInvertedAppearance(False)
        self.progressBar1_3.setObjectName("progressBar1_3")
        self.gridLayout.addWidget(self.progressBar1_3, 0, 2, 1, 1)
        self.progressBar1_4 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_4.sizePolicy().hasHeightForWidth())
        self.progressBar1_4.setSizePolicy(sizePolicy)
        self.progressBar1_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_4.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_4.setAutoFillBackground(False)
        self.progressBar1_4.setProperty("value", 25)
        self.progressBar1_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_4.setInvertedAppearance(False)
        self.progressBar1_4.setObjectName("progressBar1_4")
        self.gridLayout.addWidget(self.progressBar1_4, 0, 3, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 0, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_3.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_3.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 1, 1, 1, 1)
        self.progressBar1_2 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_2.sizePolicy().hasHeightForWidth())
        self.progressBar1_2.setSizePolicy(sizePolicy)
        self.progressBar1_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_2.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_2.setAutoFillBackground(False)
        self.progressBar1_2.setProperty("value", 25)
        self.progressBar1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_2.setInvertedAppearance(False)
        self.progressBar1_2.setObjectName("progressBar1_2")
        self.gridLayout.addWidget(self.progressBar1_2, 0, 1, 1, 1)
        self.progressBar1 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1.sizePolicy().hasHeightForWidth())
        self.progressBar1.setSizePolicy(sizePolicy)
        self.progressBar1.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1.setAutoFillBackground(False)
        self.progressBar1.setProperty("value", 25)
        self.progressBar1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1.setInvertedAppearance(False)
        self.progressBar1.setObjectName("progressBar1")
        self.gridLayout.addWidget(self.progressBar1, 0, 0, 1, 1)
        self.Connect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Connect.setObjectName("Connect")
        self.gridLayout.addWidget(self.Connect, 2, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_2.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Connect.setText(_translate("MainWindow", "Start"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
