# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1051, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(160)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar1 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1.sizePolicy().hasHeightForWidth())
        self.progressBar1.setSizePolicy(sizePolicy)
        self.progressBar1.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1.setAutoFillBackground(False)
        self.progressBar1.setProperty("value", 25)
        self.progressBar1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1.setInvertedAppearance(False)
        self.progressBar1.setObjectName("progressBar1")
        self.horizontalLayout_2.addWidget(self.progressBar1)
        self.progressBar1_2 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_2.sizePolicy().hasHeightForWidth())
        self.progressBar1_2.setSizePolicy(sizePolicy)
        self.progressBar1_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_2.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_2.setAutoFillBackground(False)
        self.progressBar1_2.setProperty("value", 25)
        self.progressBar1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_2.setInvertedAppearance(False)
        self.progressBar1_2.setObjectName("progressBar1_2")
        self.horizontalLayout_2.addWidget(self.progressBar1_2)
        self.progressBar1_3 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_3.sizePolicy().hasHeightForWidth())
        self.progressBar1_3.setSizePolicy(sizePolicy)
        self.progressBar1_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_3.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_3.setAutoFillBackground(False)
        self.progressBar1_3.setProperty("value", 25)
        self.progressBar1_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_3.setInvertedAppearance(False)
        self.progressBar1_3.setObjectName("progressBar1_3")
        self.horizontalLayout_2.addWidget(self.progressBar1_3)
        self.progressBar1_4 = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar1_4.sizePolicy().hasHeightForWidth())
        self.progressBar1_4.setSizePolicy(sizePolicy)
        self.progressBar1_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar1_4.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar1_4.setAutoFillBackground(False)
        self.progressBar1_4.setProperty("value", 25)
        self.progressBar1_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar1_4.setInvertedAppearance(False)
        self.progressBar1_4.setObjectName("progressBar1_4")
        self.horizontalLayout_2.addWidget(self.progressBar1_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_3.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_3.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout.addWidget(self.lcdNumber_3)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_2.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout.addWidget(self.lcdNumber_2)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_4.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber_4.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalLayout.addWidget(self.lcdNumber_4)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(231, 121))
        self.lcdNumber.setBaseSize(QtCore.QSize(231, 121))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Connect.setObjectName("Connect")
        self.horizontalLayout_3.addWidget(self.Connect)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Connect.setText(_translate("MainWindow", "Start"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
